#!/bin/bash

find . -name "??????.png" | xargs rm -f
find . -name "??????.jpg" | xargs rm -f
find . -name "??????.eps" | xargs rm -f

FILES=$(find . -name "*.png" )
anzahl=`find . -name "*.png" | wc -l`

counter=1
for i in $FILES
do 
  foldername=`dirname "$i"`
  tmp1=`dirname "$foldername"`
  prefix=${tmp1//_}
  prefix=${prefix//.}
  prefix=${prefix///}
  
  #random_str=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
  random_str=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 4 | head -n 1)
  
  tmp2="$prefix$random_str"
  
  target_name="$foldername/$tmp2.jpg"
  target_name_2="$foldername/$tmp2.eps"
  
  echo $foldername
  
  convert $i $target_name
  sam2p -c:jpeg -m:dpi:600 "$target_name" EPS:"$target_name_2" 

  let counter=counter+1
done

